import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC_DIR = path.join(ROOT, "scripts-src");
const OUT_DIR = path.join(ROOT, "src", "generated");
const OUT_FILE = path.join(OUT_DIR, "scripts.ts");

// Auto-injected modules
function readIfExists(filePath) {
  return fs.existsSync(filePath) ? "\n" + fs.readFileSync(filePath, "utf8") + "\n" : "";
}

const hubTagCode = readIfExists(path.join(SRC_DIR, "_hubtag.lua"));
const mm2ChatCode = readIfExists(path.join(SRC_DIR, "_mm2chat.lua"));

const TAG_INJECT_SLUGS = new Set(["mm2", "pressure", "demonology", "universal"]);
const CHAT_INJECT_SLUGS = new Set(["mm2"]);

function main() {
  if (!fs.existsSync(SRC_DIR)) {
    console.error(`scripts-src directory not found: ${SRC_DIR}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const files = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith(".lua"));
  if (files.length === 0) {
    console.error("No .lua sources found in scripts-src/");
    process.exit(1);
  }

  const entries = {};
  for (const file of files) {
    const slug = file.replace(/\.lua$/, "");
    if (slug.startsWith("_")) continue; // internal modules

    let source = fs.readFileSync(path.join(SRC_DIR, file), "utf8");
    const baseSlug = slug.replace(/_mobile$/, "");

    if (TAG_INJECT_SLUGS.has(baseSlug)) {
      source = source + hubTagCode;
    }
    if (CHAT_INJECT_SLUGS.has(baseSlug) && mm2ChatCode) {
      source = source + mm2ChatCode;
    }

    entries[slug] = source;
    console.log(`packed ${file} (${(source.length / 1024).toFixed(1)} KB raw)`);
  }

  const ts =
    `// Auto-generated by tools/obfuscate.mjs — raw bundles (no obfuscation).\n` +
    `// Served through /api/v1/script/[game].\n` +
    `export const packedScripts: Record<string, string> = ${JSON.stringify(entries, null, 2)};\n`;

  fs.writeFileSync(OUT_FILE, ts, "utf8");
  console.log(`wrote ${path.relative(ROOT, OUT_FILE)} (${(ts.length / 1024 / 1024).toFixed(2)} MB)`);
}

main();
